# Set update schedule for each package manager

version: 2
updates:
  
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    target-branch: "main"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "pip"
    directory: "/qoqo/docs"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    target-branch: "main"
    allow:
      - dependency-type: "all"
  
  - package-ecosystem: "pip"
    directory: "/qoqo/examples"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    target-branch: "main"
    allow:
      - dependency-type: "all"
  
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"