[workspace]
members = [
    "roqoqo",
    "roqoqo-derive",
    "roqoqo-test",
    "qoqo",
    "qoqo-macros"
]

[patch.crates-io]
schemars = { git = 'https://github.com/nfwvogt/schemars.git', branch="qoqo"}

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"
