[book]
authors = ["HQS Quantum Simulations <info@quantumsimulations.de>"]
language = "en"
multilingual = false
src = "src"
title = "HQS qoqo User Documentation"


[output.html]
mathjax-support = true

[preprocessor.cmdrun]
