name: HQS CI tests for rust pyo3 repos

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  linting:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_rust_pyo3.yml@main

  unittests:
    uses: mlodi-hqs/reusable_workflows/.github/workflows/reusable_unittests_rust_pyo3.yml@unittesting_features
    with:
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
      rust_package_name: "roqoqo"
      features: "json_schema"

  build_tests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_tests_rust_pyo3.yml@main
    with: 
      # Run tests also on windows runners
      windows: false
      # Run tests also on macos runners
      macos: false
      py_interface_folder: "qoqo"
      has_python_tests: false
