name: manual build debugging test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build_maturin_builds_linux:
    name: maturin_build-linux
    runs-on: 'ubuntu-20.04'
    steps:
        - uses: actions/checkout@v4
        # - uses: Swatinem/rust-cache@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            default: true
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: linux wheels
          uses: PyO3/maturin-action@v1
          with:
            maturin-version: latest
            command: build
            manylinux: 2014
            # target: x86_64-unknown-linux-gnu
            args: --out wheels -m qoqo/Cargo.toml --release --locked

  build_maturin_builds_linux_arm:
    name: maturin_build-linux-arm
    runs-on: 'ubuntu-latest'
    steps:
        - uses: actions/checkout@v3
        # - uses: Swatinem/rust-cache@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            default: true
        - uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v2
        - name: linux wheels
          uses: PyO3/maturin-action@v1
          with:
            maturin-version: latest
            command: build
            manylinux: 2014
            target: aarch64-unknown-linux-gnu
            args: --find-interpreter --out wheels -m qoqo/Cargo.toml --release --locked

  build_maturin_src_builds_linux:
    name: maturin_build-src
    runs-on: 'ubuntu-latest'
    steps:
        - uses: actions/checkout@v3
        # - uses: Swatinem/rust-cache@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            default: true
        - uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        - name: linux wheels
          uses: PyO3/maturin-action@v1
          with:
            maturin-version: latest
            command: sdist
            args: --out wheels -m qoqo/Cargo.toml