name: manual_build_maturin_macos

on:
  workflow_dispatch:
    inputs:
      py_interface_folder:
        description: "Location of the py interface folder"
        required: true
        type: string
      deploy:
        description: "Determines if build python wheels should be deployed to PyPi"
        required: false
        default: false
        type: boolean
      universal2:
        description: "Build python wheels with universal2 flag"
        required: false
        default: true
        type: boolean

jobs:

  build_maturin_builds_macos:
    name: maturin_build-macos-${{ matrix.python.interpreter }}
    runs-on: 'macOS-latest'
    strategy:
      matrix:
        python: [
            {py: '3.10', interpreter: "python3.10"},
            {py: '3.11', interpreter: "python3.11"}
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: "aarch64-apple-darwin"
          default: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest numpy twine
          python -m pip install maturin
      - name: macos wheels
        if: ${{ inputs.universal2 == false || matrix.python.py == '3.7'}}
        run: |
          RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup" maturin build -i ${{ matrix.python.interpreter }} --out wheels  -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked
      - name: universal wheels
        if: ${{ inputs.universal2 && matrix.python.py != '3.7' }}
        run: |
          RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup" maturin build -i ${{ matrix.python.interpreter }} --out wheels  -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked --target x86_64-apple-darwin
          RUSTFLAGS="-C link-arg=-undefined -C link-arg=dynamic_lookup" maturin build -i ${{ matrix.python.interpreter }} --out wheels  -m ${{inputs.py_interface_folder}}/Cargo.toml --release --locked --target aarch64-apple-darwin
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheels

  deploy:
    if: ${{inputs.deploy}}
    needs: build_maturin_builds_macos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: actions/download-artifact@v4
      with:
        name: wheels
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install twine
        python -m twine upload --skip-existing *

