name: temp_test

on:
  workflow_dispatch:


jobs:
  # Build linux wheels and upload them to PyPi
  build_maturin_builds_linux:
    name: maturin_build-linux
    uses: mlodi-hqs/reusable_workflows/.github/workflows/reusable_build_maturin_linux.yml@separate_build_folders
    with: 
      py_interface_folder: "qoqo"
      deploy: true
      # Whether to build for aarch64. Can fail if there are C/C++ dependencies
      build_for_arm: true
    secrets: inherit

  # Build macos wheels and upload them to PyPi
  build_maturin_builds_macos:
    name: maturin_build-macos
    uses: mlodi-hqs/reusable_workflows/.github/workflows/reusable_build_maturin_macos.yml@separate_build_folders
    with: 
      py_interface_folder: "qoqo"
      deploy: true
    secrets: inherit

  # Build windows wheels and upload them to PyPi
  build_maturin_builds_windows:
    name: maturin_build-windows
    uses: mlodi-hqs/reusable_workflows/.github/workflows/reusable_build_maturin_windows.yml@separate_build_folders
    with: 
      py_interface_folder: "qoqo"
      deploy: true
    secrets: inherit