name: Testing mdbook's preprocessor

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: latest
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip maturin
          pip install qoqo/[docs]
      - name: build
        run: |
          cd qoqo/docs
          python -m sphinx -T -E -b html . _build/html
          mv _build/html/* ../../documentation/src/python_api_docs
          cd ../..
          cargo install mdbook-cmdrun
          mdbook build documentation